const envConfig = {
    APPWRITE_PROJECT_URL : import.meta.env.VITE_APPWRITE_PROJECT_URL,
    APPWRITE_PROJECT_ID : import.meta.env.VITE_APPWRITE_PROJECT_ID,
    APPWRITE_DATABASE_ID : import.meta.env.VITE_APPWRITE_DATABASE_ID,
    APPWRITE_COLLECTION_ID : import.meta.env.VITE_APPWRITE_COLLECTION_ID
}

export const {APPWRITE_COLLECTION_ID, APPWRITE_DATABASE_ID, APPWRITE_PROJECT_ID, APPWRITE_PROJECT_URL} = envConfig