const envConfig = {
    APPWRITE_PROJECT_URL : String(import.meta.env.VITE_APPWRITE_PROJECT_URL),
    APPWRITE_PROJECT_ID : String(import.meta.env.VITE_APPWRITE_PROJECT_ID),
    APPWRITE_DATABASE_ID : String(import.meta.env.VITE_APPWRITE_DATABASE_ID),
    APPWRITE_COLLECTION_ID : String(import.meta.env.VITE_APPWRITE_COLLECTION_ID),
    ADMIN_EMAIL : String(import.meta.env.VITE_ADMIN_EMAIL),
}

export const {APPWRITE_COLLECTION_ID, APPWRITE_DATABASE_ID, APPWRITE_PROJECT_ID, APPWRITE_PROJECT_URL, ADMIN_EMAIL} = envConfig