const envConfig = {
  APPWRITE_PROJECT_URL: String(import.meta.env.VITE_APPWRITE_PROJECT_URL),
  APPWRITE_PROJECT_ID: String(import.meta.env.VITE_APPWRITE_PROJECT_ID),
  APPWRITE_DATABASE_ID: String(import.meta.env.VITE_APPWRITE_DATABASE_ID),
  APPWRITE_PRODUCTS_COLLECTION_ID: String(
    import.meta.env.VITE_APPWRITE_PRODUCTS_COLLECTION_ID
  ),
  APPWRITE_USER_DATA_COLLECTION_ID : String(import.meta.env.VITE_APPWRITE_USER_DATA_COLLECTION_ID),
  APPWRITE_CART_COLLECTION_ID: String(
    import.meta.env.VITE_APPWRITE_CART_COLLECTION_ID
  ),
  ADMIN_EMAIL: String(import.meta.env.VITE_ADMIN_EMAIL),
  APPWRITE_BUCKET_ID : String(import.meta.env.VITE_APPWRITE_BUCKET_ID)
};

export const {
  APPWRITE_PRODUCTS_COLLECTION_ID,
  APPWRITE_CART_COLLECTION_ID,
  APPWRITE_USER_DATA_COLLECTION_ID,
  APPWRITE_DATABASE_ID,
  APPWRITE_PROJECT_ID,
  APPWRITE_PROJECT_URL,
  ADMIN_EMAIL,
  APPWRITE_BUCKET_ID
} = envConfig;
